### ISSUE TITLE
Heyo men!

### ISSUE THREAD

**Issue by marshalldunn** [OutCore/JDA-Boilerplate#1]
@HazedSPaCEx @FireGamer3 @KillerProdsUK , I need this name, actually github.com/OutCore, so can we talk about renaming or what you can do? My mail in profile.

**Comment by HazedSPaCEx** [comment]
This is not relevant to the boilerplate so this will be closed.

**Comment by marshalldunn** [comment]
What do you mean "money"? ~10$ for this wretched domain?

**Comment by FireGamer3** [comment]
Interesting how you just signed up for GitHub 2 days ago

**Comment by marshalldunn** [comment]
@FireGamer3 Is it important now? I created a new account for my needs.

**Comment by HazedSPaCEx** [comment]
We will definitely not be renaming or anything now with how you have acted here.
